language: c

compiler:
  - clang

#https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

#dependencies 
install:
  - sudo apt-get update
  - sudo apt-get install -y wget libprotobuf-dev python-protobuf protobuf-compiler
  - sudo apt-get install -y git llvm-3.8 libclang-3.8-dev clang-3.8
  - export BUILD_HOME=`pwd`
  - export OCCAM_HOME=${BUILD_HOME}/travis_build/occam
  - export OCCAM_LOGFILE=${BUILD_HOME}/travis_build/.occam.log
  - export REPOS=${BUILD_HOME}/travis_build/Repositories

#tests
script:
  - ${BUILD_HOME}/.travis/build.sh

